name: ${APP_NAME}
networks:
  gais-network:
    external: true

volumes:
  mongodb-data:
    driver: local

services:
  mongodb:
    image: mongo:7.0
    container_name: ${APP_NAME}-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=todolist
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - gais-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${APP_NAME}:${APP_VERSION}
    pull_policy: never
    container_name: ${APP_NAME}-app
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - APP_TITLE=${APP_TITLE}
      - APP_DESCRIPTION=${APP_DESCRIPTION}
      - APP_LOGO=${APP_LOGO}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_TOKEN=${APP_TOKEN}
      - GAIS_HOST=${GAIS_HOST}
      - GAIS_PORT=${GAIS_PORT}
      - GAIS_MODEL=${GAIS_MODEL}
      - GAIS_PROTOCOL=${GAIS_PROTOCOL}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017/todolist?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    networks:
      - gais-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped